### ISSUE TITLE
Icons not displaying on blog

### ISSUE THREAD

**Issue by lithin** [redbadger/website-honestly#167] opened 2016-11-03 16:17 UTC
Go to red-badger.com/blog
Scroll to the end of an article or to the footer
Icons are displayed as letters

Problem - icon font has been deleted on website old

**Comment by asavin** [comment] 2016-11-03 16:26
There is a CORS related issue that prevents webfonts from red-badger.com to load on the blog. The fix could be to allow access to red-badger.com on `http` or to move blog to `https`.

**Comment by Roisi** [comment] 2016-11-04 10:09
dupe of #155 so closing

**Closed by Roisi** 2016-11-04 10:09 UTC
Labels: Bug
