### ISSUE TITLE
Twitter and Profile links on blog look funny

### ISSUE THREAD

**Issue by robbiemccorkell** [redbadger/website-honestly#166] opened 2016-11-03 15:47 UTC
At the bottom of a blog post the twitter and profile links are showing up as `!` and `?` characters respectively.

E.g. http://red-badger.com/blog/2015/06/02/yosemite-by-cocoaconf-zen-and-the-art-of-tech-conferences/

<img width="601" alt="screen shot 2016-11-03 at 15 45 58" src="https://cloud.githubusercontent.com/assets/2011550/19973320/ca6b469a-a1dc-11e6-8c6d-0c349db6ca8c.png">

**Comment by Roisi** [comment] 2016-11-04 10:09
Dupe of #155 so closing

**Closed by Roisi** 2016-11-04 10:09 UTC
