### ISSUE TITLE
Homepage signup button is not rendering

### ISSUE THREAD

**Issue by pataruco** [redbadger/website-honestly#917] opened 2020-03-26 22:27 UTC
<img width="1651" alt="Screenshot 2020-03-26 at 22 20 15" src="https://user-images.githubusercontent.com/10330222/77702433-69e89980-6fb0-11ea-8bbb-bcd20d91e823.png">

### Expected Behaviour
In the homepage on the **Sign up to Badger News** I expect to see a styled sign up button

### Actual Behaviour
In the homepage on the **Sign up to Badger News** I see a plain HTML link

### Steps to Reproduce
Go to https://red-badger.com/ scroll down to **Sign up to Badger News*

### OS/Browsers Affected
ALL

**Comment by kephail** [comment] 2020-03-27 09:40
Is there somewhere we can access designs for the site to know what this should look like?

**Comment by kephail** [comment] 2020-03-27 09:42
Actually, this is rendering just fine for me.

<img width="612" alt="Screenshot 2020-03-25 at 19 57 31" src="https://user-images.githubusercontent.com/3603778/77742934-312bdd00-700f-11ea-83ae-67aa966edb2d.png">

**Comment by SiAshbery** [comment] 2020-04-06 09:29
Unable to reproduce but @pataruco is still encountering the issue. He's having a look into it at his end.

For now I am closing the issue unless we discover that it is a wider issue.

**Closed by SiAshbery** 2020-04-06 09:29 UTC
Labels: Bug, High
