### ISSUE TITLE
News subscription and Tell us more input boxes should be removed or blocked when in non-JS

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#403] opened 2017-03-08 18:22 UTC
**Description of the issue:**
The News Subscription and Tell Us More input boxes are still active when in non-JS. The boxes should be inactive or hidden, and the sentence saying what to do when JS is off should be more obvious to the customer.

**Browser used:**
All browsers

**Steps to reproduce:**
Tell us more input:
1. Turn off JavaScript
2. On the home page scroll down to the "Project in mind? Tell us more." section.
3. View the 'Message' and 'Your email' input boxes and the submit button.
4. View the JavaScript disabled sentence below. 

![screen shot 2017-03-08 at 17 48 16](https://cloud.githubusercontent.com/assets/9529865/23717187/ad5d45de-042a-11e7-8a4f-d3d2f8a40fa0.png)

Badger News Signup:
1. Turn off JavaScript
2. On the home page scroll down to the "Sign up to Badger News" section.
3. View the Email input box and the Sign Up button.
4. View the JavaScript disabled sentence below. 

![screen shot 2017-03-08 at 17 47 29](https://cloud.githubusercontent.com/assets/9529865/23717259/0127fc5e-042b-11e7-8f36-740d159625b4.png)

**Actual result:**
The input boxes are active and you can write in them and click the buttons, so it looks like the messages are sent.

**Expected result:**
The input boxes should be blocked or hidden. If the boxes are left on the page the sentence about the JS being off and what you should do, should be more obvious to the user. (See designers for their opinion).

**Comment by grahammendick** [comment] 2017-03-09 09:57
@chris-brookes Can we close because it's a duplicate of #187?

**Comment by chris-brookes** [comment] 2017-03-09 10:03
@grahammendick - Ah yeah I didn't find that entry. I'll close this one.

**Closed** 2017-03-09 10:03 UTC
