### ISSUE TITLE
Mobile nav on blog too large font size

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#265] opened 2016-12-15 09:55 UTC
![slack for ios upload-5](https://cloud.githubusercontent.com/assets/16961478/21219076/26490f4e-c2ab-11e6-90b8-c1ce6042596a.jpg)
Font size on a mobile nav on our blog is too large. Can it match the sizes on other sections of the page?

**Comment by Roisi** [comment] 2016-12-15 10:08
dupe of #195 so closing

**Closed by Roisi** 2016-12-15 10:08 UTC
