### ISSUE TITLE
All 'about us timeline' content is shown if javascript is disabled

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#332] opened 2017-01-13 12:48 UTC
- Turn off javascript
- Go to /about-us

You'll see every year's content. I'd imagine it should maybe just show the current year?

**Comment by asavin** [comment] 2017-01-13 15:31
That's functions as intended - this is a fallback for no-js browser

**Comment by Roisi** [comment] 2017-01-17 13:24
closing functions as intended

**Closed by Roisi** 2017-01-17 13:24 UTC
Labels: Bug
