### ISSUE TITLE
[Blog] horizontal scrolling on iphone 5s

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#210] opened 2016-12-01 14:40 UTC
The blog listing page scrolls horizontally even though there is no need for it.
Can we please remove it? 

(this doesn't happen on the blog post page)

**Comment by tabazevedo** [comment] 2016-12-01 14:42
@Monikamu I can't seem to reproduce this on Chrome. What browser are you seeing this on?

**Comment by Monikamu** [comment] 2016-12-01 14:46
Strange – Chrome

**Comment by tabazevedo** [comment] 2016-12-01 15:23
Sorry yep. Didn't read iPhone 5S. Can't reproduce in Chrome Responsive mode or on my Nexus 5. Bug seems to be due to video extending past the screen. It still extends past the screen on my phone but on the iPhone it also stretches the page.

**Comment by Roisi** [comment] 2017-01-17 13:07
@samsmith1983 to recheck

**Comment by samsmith1983** [comment] 2017-01-17 15:19
Yep, can repro on iPhone 5s with iOS10.

**Comment by samsmith1983** [comment] 2017-01-25 13:40
^ This is now fixed

**Closed by samsmith1983** 2017-01-25 13:40 UTC
Labels: Bug
